'use client';

import { usePOS } from '@/lib/context/pos-context';
import { useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Printer } from 'lucide-react';

export function useReceiptPrinter() {
  const { state } = usePOS();
  const printRef = useRef<HTMLDivElement>(null);

  const generateReceipt = () => {
    const { cart, currentCustomer } = state;
    const invoiceDate = new Date().toLocaleDateString('en-IN');
    const invoiceTime = new Date().toLocaleTimeString('en-IN');

    return `
    ╔════════════════════════════════════╗
    ║      ABC CORPORATION PVT LTD       ║
    ║   GSTIN: 27AABCT1234C1Z5           ║
    ║   Hyderabad, Telangana             ║
    ╚════════════════════════════════════╝
    
    ────────────────────────────────────
    INVOICE DETAILS
    ────────────────────────────────────
    Date: ${invoiceDate}
    Time: ${invoiceTime}
    Invoice #: ${cart.id}
    Terminal: POS-01
    
    ${
      currentCustomer
        ? `Customer: ${currentCustomer.name}
    Phone: ${currentCustomer.phone}
    GSTIN: ${currentCustomer.gstin || 'N/A'}`
        : 'Customer: Cash'
    }
    
    ────────────────────────────────────
    ITEMS
    ────────────────────────────────────
    ${cart.lineItems
      .map(
        (item) => `
    ${item.productName}
    Qty: ${item.quantity} × ₹${item.unitPrice.toFixed(2)} = ₹${item.lineTotal.toFixed(2)}
    Tax: ${item.taxRate}% (₹${item.taxAmount.toFixed(2)})`
      )
      .join('\n')}
    
    ────────────────────────────────────
    TOTALS
    ────────────────────────────────────
    Subtotal:        ₹${cart.subtotal.toLocaleString('en-IN')}
    ${
      cart.discount.amount > 0
        ? `Discount:        -₹${cart.discount.amount.toLocaleString('en-IN')}\n`
        : ''
    }
    ────────────────────────────────────
    Tax Breakdown:
      CGST (9%):    ₹${cart.taxBreakdown.cgst.toFixed(2)}
      SGST (9%):    ₹${cart.taxBreakdown.sgst.toFixed(2)}
      IGST (18%):   ₹${cart.taxBreakdown.igst.toFixed(2)}
    ────────────────────────────────────
    TOTAL AMOUNT:    ₹${cart.totalAmount.toLocaleString('en-IN')}
    
    ────────────────────────────────────
    Payment Method: ${cart.paymentMethod || 'Cash'}
    Status: ${cart.status === 'completed' ? 'PAID' : 'PENDING'}
    
    ────────────────────────────────────
    Thank you for your purchase!
    Visit again soon.
    
    Generated by GST Billing System
    ${new Date().toISOString()}
    ════════════════════════════════════
    `;
  };

  const printReceipt = () => {
    const receipt = generateReceipt();
    const printWindow = window.open('', '', 'height=600,width=400');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Receipt</title>
            <style>
              body {
                font-family: 'Courier New', monospace;
                margin: 0;
                padding: 10px;
                font-size: 12px;
                line-height: 1.4;
              }
              pre {
                white-space: pre-wrap;
                word-wrap: break-word;
              }
            </style>
          </head>
          <body>
            <pre>${receipt}</pre>
          </body>
        </html>
      `);
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
      }, 100);
    }
  };

  return { generateReceipt, printReceipt };
}

export function ReceiptPreview() {
  const { state } = usePOS();
  const { generateReceipt, printReceipt } = useReceiptPrinter();

  return (
    <div className="space-y-4">
      <div className="bg-slate-100 p-4 rounded-lg border border-slate-300 overflow-auto max-h-96">
        <pre className="text-xs font-mono whitespace-pre-wrap break-words">
          {generateReceipt()}
        </pre>
      </div>

      <Button
        onClick={printReceipt}
        className="w-full gap-2 bg-blue-600 hover:bg-blue-700"
      >
        <Printer className="w-4 h-4" />
        Print Receipt (F6)
      </Button>
    </div>
  );
}
